// Code generated by interfacer; DO NOT EDIT

package factory

import (
	"context"
	"github.com/google/go-github/v33/github"
	"io"
	"net/http"
)

// GithubClient is an interface generated for "github.com/google/go-github/v33/github.Client".
type GithubClient interface {
	APIMeta(context.Context) (*github.APIMeta, *github.Response, error)
	Do(context.Context, *http.Request, interface{}) (*github.Response, error)
	GetCodeOfConduct(context.Context, string) (*github.CodeOfConduct, *github.Response, error)
	ListCodesOfConduct(context.Context) ([]*github.CodeOfConduct, *github.Response, error)
	ListEmojis(context.Context) (map[string]string, *github.Response, error)
	ListServiceHooks(context.Context) ([]*github.ServiceHook, *github.Response, error)
	Markdown(context.Context, string, *github.MarkdownOptions) (string, *github.Response, error)
	NewRequest(string, string, interface{}) (*http.Request, error)
	NewUploadRequest(string, io.Reader, int64, string) (*http.Request, error)
	Octocat(context.Context, string) (string, *github.Response, error)
	RateLimits(context.Context) (*github.RateLimits, *github.Response, error)
	Zen(context.Context) (string, *github.Response, error)
}
