name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  job-test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: v33/go.mod

      - name: Run lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          workdir: v33/
          fail_level: any
          go_version_file: v33/go.mod
          golangci_lint_flags: '--config=../.golangci.yml'

      - name: Test
        run: make ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run octocov
        uses: k1LoW/octocov-action@v1

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
